package com.esh7enly.domain.entity.chargebalancerequest

data class ChargeBalanceRequestPaytabs(
    var id: Int?= null,
    var amount: String?= null,
    var card_id: String?= null,
    var total_amount: String?= null,
    var cartDescription:String?= null,
    var errorCode:String?= null,
    var errorMsg:String?= null,
    var isAuthorized:Boolean?= null,
    var isOnHold:Boolean?= null,
    var isPending:Boolean?= null,
    var isProcessed:Boolean?= null,
    var isSuccess:Boolean?= null,
    var payResponseReturn:String?= null,
    var redirectUrl:String?= null,
    var token:String?= null,
    var transactionReference:String?= null,
    var transactionType:String?= null,
    var responseCode:String?= null,
    var responseMessage:String?= null,
    var responseStatus:String?= null,
    var transactionTime:String?= null,
    var cardScheme:String?= null,
    var cardType:String?= null,
    var paymentDescription:String?= null,
    var total_amount_currency: String?= null,
    var status: String?= null,
    var total_amount_piasters: String?= null,
    var payment_method_type:String?= null,
    var transaction_type:String?= null,
    var hash_generated:String?= null,
    var hash_id:String?= null
)
